version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: sonicboom24/backend:1.0

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: sonicboom24/frontend:1.0